### ISSUE TITLE
support lower version of python3

### ISSUE THREAD

**Issue by noword** [kynex7510/nds_ida#1]
It seems the only reason that not compatible with older version is `str.removesuffix`

```
from pathlib import Path
# script_path = script_path.removesuffix(script_name) + "../nds"
script_path = str(Path(script_path).parent / '../nds')
```
It works in my python 3.8, and pathlib has been available since version 3.4

Thanks for your great work, it really helps me。

**Comment by kynex7510** [comment]
Appreciate the interest, though I'm not working on the project anymore.
